### ISSUE TITLE
Unable to run at linux "Não foi possível localizar nem carregar a classe principal ..lib.bsh-2.0b5.jar"

### ISSUE THREAD

**Issue by LeonanCarvalho** [L2jBrasil/L2jBrasil#27]
### Description
Trying to deploy a test server I realized that something wrong to run the server at linux.

### How To reproduce:
You can use the [Dockerfile](https://github.com/L2jBrasil/L2jBrasil/blob/develop/docker-images/l2jserver/Dockerfile) or install by yourself at a CentOS7 (I think it's not an isolated by SO)
Running these commands:
```
# you can build here, or donload the latest release
# I'll download the latest.
yum install java-1.8.0-openjdk wget -y
export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64/
export CLASSPATH=.:$JAVA_HOME
wget https://github.com/L2jBrasil/L2jBrasil/releases/download/3.0.2/L2JBrasil_3.0.2.zip
unzip L2JBrasil_3.0.2.zip
cd L2JBrasil_3.0.2
unzip L2JBrasil_CORE.zip -d .
#Type "A"
unzip L2JBrasil_DP.zip -d .
#Type "A"
cd Game
# Try to run  any program:
java -cp ./lib/* com.it.br.gsregistering.GameServerRegister
#ERROR
java -Xmx32m -XX:+UseParallelGC -XX:+AggressiveOpts -XX:ParallelGCThreads=2  -cp ./lib/* com.it.br.loginserver.L2LoginServer
#ERROR
java -Xmx512m -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+HeapDumpOnOutOfMemoryError -cp ./lib/* com.it.br.gameserver.GameServer
#ERROR
```

All try to run returns the same error.

**Comment by JoeAlisson** [comment]
You just need to put the classpath value ( ./lib/* )  between quotes.

" * " is a command in bash scripting.

**Comment by LeonanCarvalho** [comment]
Realmente era isso que faltava, mas aparentemente os arquivos de configuração não estão sendo buscados de forma relativa e sim estática na raíz de onde o comando está sendo executado.
Seria isso um possível erro?

```
l2jserver_1  | java.io.FileNotFoundException: ./config/other/log.cfg (No such file or directory)
l2jserver_1  |  at java.io.FileInputStream.open0(Native Method)
l2jserver_1  |  at java.io.FileInputStream.open(FileInputStream.java:195)
l2jserver_1  |  at java.io.FileInputStream.<init>(FileInputStream.java:138)
l2jserver_1  |  at com.it.br.loginserver.L2LoginServer.<init>(L2LoginServer.java:81)
l2jserver_1  |  at com.it.br.loginserver.L2LoginServer.main(L2LoginServer.java:57)
l2jserver_1  | java.io.FileNotFoundException: ./config/login.properties (No such file or directory)
l2jserver_1  |  at java.io.FileInputStream.open0(Native Method)
l2jserver_1  |  at java.io.FileInputStream.open(FileInputStream.java:195)
l2jserver_1  |  at java.io.FileInputStream.<init>(FileInputStream.java:138)
l2jserver_1  |  at com.it.br.Config.loadLoginServerConfig(Config.java:3118)
l2jserver_1  |  at com.it.br.Config.load(Config.java:3729)
l2jserver_1  |  at com.it.br.loginserver.L2LoginServer.<init>(L2LoginServer.java:106)
l2jserver_1  |  at com.it.br.loginserver.L2LoginServer.main(L2LoginServer.java:57)
l2jserver_1  | Exception in thread "main" java.lang.Error: Failed to Load ./config/login.properties File.
l2jserver_1  |  at com.it.br.Config.loadLoginServerConfig(Config.java:3153)
l2jserver_1  |  at com.it.br.Config.load(Config.java:3729)
l2jserver_1  |  at com.it.br.loginserver.L2LoginServer.<init>(L2LoginServer.java:106)
l2jserver_1  |  at com.it.br.loginserver.L2LoginServer.main(L2LoginServer.java:57)
```

**Comment by LeonanCarvalho** [comment]
@Tayran  Eu fechei o issue pois realmente só faltava as aspas... mas gostaria que você verificasse a questão do script requerendo o arquivo de configuração à partir de "./config/", não é uma boa prática ele utilizar o diretório de execução como base dir da execução.

O ideal é utilizar o base dir previamente definido pelo usuário através de parâmetros ou utilizar com base do path do executável.

Ref. https://stackoverflow.com/questions/16239130/java-user-dir-property-what-exactly-does-it-mean
