### ISSUE TITLE
Unable to conect on mysql 

### ISSUE THREAD

**Issue by LeonanCarvalho** [L2jBrasil/L2jBrasil#43]
[PT-BR]
A configuração do docker foi concluida porém estou recebendo o seguinte erro tanto no login server como no game server (anexo )

O mysql do container docker roda no ip `10.2.0.4` , essa configuração foi realizada nos arquivos server.properties e login.properties  porém algo ainda está errado.

[EN]
The docker configuration has been completed but I'm getting the following error on both the login server and the game server (attachment )

The mysql of the docker container runs on ip `10.2.0.4`, this configuration was done in the server.properties and login.properties files however something is still wrong.

### Anexos/ Attachments (printscreen, links ,etc )
```
ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
Exception in thread "main" com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:545)
at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:537)
at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
at com.it.br.L2DatabaseFactory.<init>(L2DatabaseFactory.java:60)
at com.it.br.L2DatabaseFactory.getInstance(L2DatabaseFactory.java:124)
at com.it.br.gameserver.GameServer.main(GameServer.java:571)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2222)
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2017)
at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
... 5 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
... 23 more
```

**Comment by JoeAlisson** [comment]
@LeonanCarvalho verifica se o mysql está aceitando conexões remotas. Se a configuração 'bind-address' estiver  '127.0.0.1', ele apenas aceitará conexões de localhost. 

Outra configuração que também impede o acesso remoto é  o 'skip-networking'.

Você pode verificar se o mysql está aceitando conexões externas utilizando o comando netstat

`netstat -ntlup | grep mysql`

Vale à pena também tentar conectar utilizando telnet, a partir do container do server, para descartar erros de configuração.

`telnet 10.2.0.4 3306 `

E por último, não acredito que seja o caso, mas em um dos commits recentes da branch 'develop' a configuração de conexão com o banco de dados foi mudada para o arquivo 'database.properties'

**Comment by LeonanCarvalho** [comment]
Vou fazer esse teste,

Eu adicionei a pasta o arquivo de configuração do mysql: https://github.com/L2jBrasil/L2jBrasil/blob/develop/docker-images/mysql/mysqld.cnf

Eu botei o `bind-address`  para `0.0.0.0` 


Para o gameserver e login server eu adicionei a pasta config: https://github.com/L2jBrasil/L2jBrasil/tree/develop/docker-images/l2jserver/config , todos os arquivos nela sobrescrevem os arquivos do projeto, ou adicionam na respectiva pasta. É uma forma de poder customizar o gameserver de uma forma mais prática do que [usando a linha de comando](https://github.com/L2jBrasil/L2jBrasil/blob/develop/docker-images/l2jserver/Dockerfile#L46). 

Vou atualizar o arquivo do docker, tinha um espaço na linha de senha e fazer esses testes de dentro do container do java game/login também.
