### ISSUE TITLE
Problemas com funções dentro de scripts de quests

### ISSUE THREAD

**Issue by Anderuimm** [L2jBrasil/L2jBrasil#46]
### Descrição/Description
Quest "Letters of Love" bugada: o NPC Darin, na última parte da missão, pega a poção mas não entrega as recompensas nem finaliza a quest.

Erro:
```
/interlude/Game/data/jscript/quests/1_LettersOfLove/__init__.py
Traceback (innermost last):
  File "__init__.py", line 109, in onTalk
AttributeError: rewardItems

	at org.python.core.Py.AttributeError(Unknown Source)
	at org.python.core.PyInstance.invoke(Unknown Source)
	at org.python.pycode.serializable._pyx1511999288219.onTalk$4(__init__.py:109)
	at org.python.pycode.serializable._pyx1511999288219.call_function(__init__.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject._jcallexc(Unknown Source)
	at org.python.core.PyObject._jcall(Unknown Source)
	at org.python.proxies.main$Quest$27.onTalk(Unknown Source)
	at com.it.br.gameserver.model.quest.Quest.notifyTalk(Quest.java:509)
	at com.it.br.gameserver.model.actor.instance.L2NpcInstance.showQuestWindow(L2NpcInstance.java:1291)
	at com.it.br.gameserver.model.actor.instance.L2NpcInstance.showQuestWindow(L2NpcInstance.java:1354)
	at com.it.br.gameserver.model.actor.instance.L2NpcInstance.onBypassFeedback(L2NpcInstance.java:945)
	at com.it.br.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:149)
	at com.it.br.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gitrcadigital** [comment]
Verifiquei nos logs e outras missões tem o mesmo problema:

/interlude/Game/data/jscript/quests/259_RanchersPlea/__init__.py
/interlude/Game/data/jscript/quests/999_InterludeTutorial/__init__.py


E outras aparecem problemas diferentes:
```

/interlude/Game/data/jscript/quests/39_RedEyedInvaders/__init__.py
Traceback (innermost last):
  File "__init__.py", line 121, in onKill
  File "__init__.py", line 42, in drop
NameError: Config

	at org.python.core.Py.NameError(Unknown Source)
	at org.python.core.PyFrame.getglobal(Unknown Source)
	at org.python.pycode.serializable._pyx1511999288511.drop$1(__init__.py:42)
	at org.python.pycode.serializable._pyx1511999288511.call_function(__init__.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.pycode.serializable._pyx1511999288511.onKill$6(__init__.py:121)
	at org.python.pycode.serializable._pyx1511999288511.call_function(__init__.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject._jcallexc(Unknown Source)
	at org.python.core.PyObject._jcall(Unknown Source)
	at org.python.proxies.main$Quest$64.onKill(Unknown Source)
	at com.it.br.gameserver.model.quest.Quest.notifyKill(Quest.java:492)
	at com.it.br.gameserver.model.L2Attackable.doDie(L2Attackable.java:446)
	at com.it.br.gameserver.model.actor.instance.L2MonsterInstance.doDie(L2MonsterInstance.java:208)
	at com.it.br.gameserver.model.actor.status.CharStatus.reduceHp(CharStatus.java:217)
	at com.it.br.gameserver.model.actor.status.NpcStatus.reduceHp(NpcStatus.java:50)
	at com.it.br.gameserver.model.L2Character.reduceCurrentHp(L2Character.java:6888)
	at com.it.br.gameserver.model.L2Attackable.reduceCurrentHp(L2Attackable.java:394)
	at com.it.br.gameserver.model.L2Attackable.reduceCurrentHp(L2Attackable.java:346)
	at com.it.br.gameserver.handler.skillhandlers.Mdam.useSkill(Mdam.java:199)
	at com.it.br.gameserver.model.L2Character.callSkill(L2Character.java:6486)
	at com.it.br.gameserver.model.L2Character.onMagicHitTimer(L2Character.java:6114)
	at com.it.br.gameserver.model.L2Character$MagicUseTask.run(L2Character.java:2299)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```


**Detalhe importante:** isso não acontece em todas as quests, apenas nas que citei até o momento. Fiz várias missões com um anão e jogadores fizeram quests de 1ª Job e estas estão funcionando normalmente.

**Comment by Anderuimm** [comment]
Verifiquei nos logs e outras missões tem o mesmo problema:

```
/interlude/Game/data/jscript/quests/259_RanchersPlea/init.py
/interlude/Game/data/jscript/quests/999_InterludeTutorial/init.py
```

E outras aparecem problemas diferentes:

```
/interlude/Game/data/jscript/quests/39_RedEyedInvaders/__init__.py
Traceback (innermost last):
  File "__init__.py", line 121, in onKill
  File "__init__.py", line 42, in drop
NameError: Config

	at org.python.core.Py.NameError(Unknown Source)
	at org.python.core.PyFrame.getglobal(Unknown Source)
	at org.python.pycode.serializable._pyx1511999288511.drop$1(__init__.py:42)
	at org.python.pycode.serializable._pyx1511999288511.call_function(__init__.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.pycode.serializable._pyx1511999288511.onKill$6(__init__.py:121)
	at org.python.pycode.serializable._pyx1511999288511.call_function(__init__.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject._jcallexc(Unknown Source)
	at org.python.core.PyObject._jcall(Unknown Source)
	at org.python.proxies.main$Quest$64.onKill(Unknown Source)
	at com.it.br.gameserver.model.quest.Quest.notifyKill(Quest.java:492)
	at com.it.br.gameserver.model.L2Attackable.doDie(L2Attackable.java:446)
	at com.it.br.gameserver.model.actor.instance.L2MonsterInstance.doDie(L2MonsterInstance.java:208)
	at com.it.br.gameserver.model.actor.status.CharStatus.reduceHp(CharStatus.java:217)
	at com.it.br.gameserver.model.actor.status.NpcStatus.reduceHp(NpcStatus.java:50)
	at com.it.br.gameserver.model.L2Character.reduceCurrentHp(L2Character.java:6888)
	at com.it.br.gameserver.model.L2Attackable.reduceCurrentHp(L2Attackable.java:394)
	at com.it.br.gameserver.model.L2Attackable.reduceCurrentHp(L2Attackable.java:346)
	at com.it.br.gameserver.handler.skillhandlers.Mdam.useSkill(Mdam.java:199)
	at com.it.br.gameserver.model.L2Character.callSkill(L2Character.java:6486)
	at com.it.br.gameserver.model.L2Character.onMagicHitTimer(L2Character.java:6114)
	at com.it.br.gameserver.model.L2Character$MagicUseTask.run(L2Character.java:2299)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```


**Detalhe importante:** isso não acontece em todas as quests, apenas nas que citei até o momento. Fiz várias missões com um anão e jogadores fizeram quests de 1ª Job e estas estão funcionando normalmente.

**Comment by Anderuimm** [comment]
Iniciei um servidor em uma máquina com Java 8 recém instalado, S.O. Windows 10 Pro x64, MySQL 5.6, com um personagem não-admin, rate x10 XP (foi a única configuração além da conexão com o banco que eu mudei), e o banco de dados recém instalado. O mesmo problema citado de não completar a _Letters of Love_ ocorreu.

**Comment by Tayran** [comment]
Muito obrigado pelo report, estaremos olhando todos e consertando esses erros, o banco é 5.7 mas não influenciará nesses erros não, só no desempenho.

**Comment by Anderuimm** [comment]
Pergunto, @Tayran: as quests do serverpack da Frozen são compatíveis? Posso testar essas que citei nele,  tenho uma cópia aqui.

Sobre o banco de dados, em produção utilizo o 5.7 mesmo.

**Comment by LeonardoHolanda** [comment]
@Anderuimm, as quests Letters Of Love, Ranchers Plea e Red Eyed Invaders já foram fixadas, mais tarde farei o commit.

**Comment by Tayran** [comment]
Não, muita coisa bate e outras não, e muita coisa na Frozen ta fora de padrão fazendo que ela não sirva de base, o que precisamos realmente é saber o comportamento da Quest original, e nós nos encarregaremos de deixar ela funcionando como a original.

**Comment by Anderuimm** [comment]
- Sword of Solidarity [Nível 9]: reportaram que ela não entregou as recompensas devidas, que seriam uma Sword of Solidarity (único item entregue), 100 Lesser Healing Potions, 50 Echo Crystals variados, 10,981 em adenas, 25,747 em experiência e 2,171 em SP.
- Spirit of Mirrors [Nível 10]: reportaram que ela entregou apenas 500 Spiritshots, e na descrição ela daria: Wand of Adept, 100 Lesser Healing Potions, 3,500 Newbie Spiritshots, 50 Echo Crystals variados, 37,750 em experiência e 3,407 em SP.

**Comment by Anderuimm** [comment]
Erros capturados no meu ogger:


```
/interlude/Game/data/jscript/quests/104_SpiritOfMirrors/__init__.py
Traceback (innermost last):
  File "__init__.py", line 80, in onTalk
AttributeError: rewardItems

	at org.python.core.Py.AttributeError(Unknown Source)
	at org.python.core.PyInstance.invoke(Unknown Source)
	at org.python.pycode.serializable._pyx1512051363101.onTalk$5(__init__.py:80)
	at org.python.pycode.serializable._pyx1512051363101.call_function(__init__.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject._jcallexc(Unknown Source)
	at org.python.core.PyObject._jcall(Unknown Source)
	at org.python.proxies.main$Quest$112.onTalk(Unknown Source)
	at com.it.br.gameserver.model.quest.Quest.notifyTalk(Quest.java:509)
	at com.it.br.gameserver.model.actor.instance.L2NpcInstance.showQuestWindow(L2NpcInstance.java:1291)
	at com.it.br.gameserver.model.actor.instance.L2NpcInstance.onBypassFeedback(L2NpcInstance.java:947)
	at com.it.br.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:149)
	at com.it.br.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```


```
/interlude/Game/data/jscript/quests/999_InterludeTutorial/__init__.py
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at com.it.br.gameserver.model.quest.QuestState.exitQuest(QuestState.java:851)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyInstance.invoke(Unknown Source)
	at org.python.pycode.serializable._pyx1512051365245.onFirstTalk$4(__init__.py:152)
	at org.python.pycode.serializable._pyx1512051365245.call_function(__init__.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject._jcallexc(Unknown Source)
	at org.python.core.PyObject._jcall(Unknown Source)
	at org.python.proxies.main$Quest$368.onFirstTalk(Unknown Source)
	at com.it.br.gameserver.model.quest.Quest.notifyFirstTalk(Quest.java:526)
	at com.it.br.gameserver.model.actor.instance.L2NpcInstance.onAction(L2NpcInstance.java:680)
	at com.it.br.gameserver.model.actor.instance.L2PcInstance.doInteract(L2PcInstance.java:3928)
	at com.it.br.gameserver.model.actor.instance.L2PcInstance$AIAccessor.doInteract(L2PcInstance.java:148)
	at com.it.br.gameserver.ai.L2PlayerAI.thinkInteract(L2PlayerAI.java:307)
	at com.it.br.gameserver.ai.L2PlayerAI.onEvtThink(L2PlayerAI.java:345)
	at com.it.br.gameserver.ai.L2CharacterAI.onEvtArrived(L2CharacterAI.java:749)
	at com.it.br.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:401)
	at com.it.br.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.it.br.gameserver.GameTimeController$MovingObjectArrived.run(GameTimeController.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
/interlude/Game/data/jscript/quests/101_SwordOfSolidarity/__init__.py
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at com.it.br.gameserver.model.quest.QuestState.exitQuest(QuestState.java:851)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyInstance.invoke(Unknown Source)
	at org.python.pycode.serializable._pyx1512051363062.onEvent$3(__init__.py:46)
	at org.python.pycode.serializable._pyx1512051363062.call_function(__init__.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject._jcallexc(Unknown Source)
	at org.python.core.PyObject._jcall(Unknown Source)
	at org.python.proxies.main$Quest$109.onEvent(Unknown Source)
	at com.it.br.gameserver.model.quest.Quest.onAdvEvent(Quest.java:740)
	at com.it.br.gameserver.model.quest.Quest.notifyEvent(Quest.java:456)
	at com.it.br.gameserver.model.actor.instance.L2PcInstance.processQuestEvent(L2PcInstance.java:1314)
	at com.it.br.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:203)
	at com.it.br.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
No item handler registered for item ID 8542.
```

**Comment by Tayran** [comment]
`No item handler registered for item ID 8542.`

esse de cima ai não é erro, só aviso que alguém tentou usar um item normal como itens equipáveis e etc.

Agradeço toda a ajuda que ta dando, eu vou mexer nisso tudo assim que tiver um tempo livre, ta muito corrido para mim as coisas essa semana.

**Comment by Anderuimm** [comment]
Log de erro de mais uma quest:

```
/interlude/Game/data/jscript/quests/112_WalkOfFate/__init__.py
Traceback (innermost last):
  File "__init__.py", line 45, in onTalk
AttributeError: class 'com.it.br.gameserver.model.quest.State' has no attribute 'COMPLETED'

	at org.python.core.Py.AttributeError(Unknown Source)
	at org.python.core.PyObject.noAttributeError(Unknown Source)
	at org.python.core.PyObject.__getattr__(Unknown Source)
	at org.python.pycode.serializable._pyx1512051363180.onTalk$4(__init__.py:45)
	at org.python.pycode.serializable._pyx1512051363180.call_function(__init__.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject._jcallexc(Unknown Source)
	at org.python.core.PyObject._jcall(Unknown Source)
	at org.python.proxies.main$Quest$120.onTalk(Unknown Source)
	at com.it.br.gameserver.model.quest.Quest.notifyTalk(Quest.java:509)
	at com.it.br.gameserver.model.actor.instance.L2NpcInstance.showQuestWindow(L2NpcInstance.java:1291)
	at com.it.br.gameserver.model.actor.instance.L2NpcInstance.onBypassFeedback(L2NpcInstance.java:947)
	at com.it.br.gameserver.model.actor.instance.L2FolkInstance.onBypassFeedback(L2FolkInstance.java:310)
	at com.it.br.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:149)
	at com.it.br.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by LeonardoHolanda** [comment]
Quests 101, 104 e 112 [Fixadas.](https://github.com/L2jBrasil/L2jBrasil/commit/47a1f34814c26f588e6c5f4d7a3ba57a962baeab)

**Comment by Tayran** [comment]
Galera pelo que vi todos foram fixados ou quase todos, se algum voltar a retornar a aparecer erro, abram um novo Issue, e para manter a organizado façam 1 issue para cada quest com erro. Obrigado.
