### ISSUE TITLE
Erro no Encantamento de Itens

### ISSUE THREAD

**Issue by AnibalDuarte** [L2jBrasil/L2jBrasil#59]
Ao tentar utilizar um Enchant ocorre esse erro:

> 
> Client: [Character: PaiPlayer - Account: paiplayer - IP: ***.***.***.***] - Failed running: [C] 58 RequestEnchantItem
> java.lang.NullPointerException
>         at com.it.br.gameserver.model.L2ItemInstance.getMaxEnchantCustom(L2ItemInstance.java:402)
>         at com.it.br.gameserver.network.clientpackets.RequestEnchantItem.runImpl(RequestEnchantItem.java:87)
>         at com.it.br.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:85)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)

Segue abaixo o arquivo enchant.properties :
```

# --------------------------------------- #
# -      L2JBrasil Enchant Settings     - #
# --------------------------------------- #
# % Chance of succeeding to enchant an item when it has a chance of breaking
# Default: 68 | 52 | 54
EnchantChanceWeapon = 66
EnchantChanceArmor = 66
EnchantChanceJewelry = 66

# Chance a Crystal Enchant Scroll will succeed after safe enchant.
# Default: 100 | 100 | 100
EnchantChanceWeaponCrystal = 100
EnchantChanceArmorCrystal = 100
EnchantChanceJewelryCrystal = 100

# Chance a Blessed Enchant Scroll will succeed after safe enchant.
# Default: 85 | 85 | 85
EnchantChanceWeaponBlessed = 75
EnchantChanceArmorBlessed = 75
EnchantChanceJewelryBlessed = 75

# ------------------------------------------- #
# -    Config Chance Scroll Enchant Itens   - #
# ------------------------------------------- #
# Alternative system Enchant Scroll Weapon
EnableEnchantChanceScrollWeapon = False
ChanceScrollWeaponList = 3,66;4,63;5,60;6,57;7,54;8,51;9,48;10,45;11,42;12,39;13,36;14,33;15,30

# Alternative system Enchant Scroll Armor
EnableEnchantChanceScrollArmor = False
ChanceScrollArmorList = 3,66;4,63;5,60;6,57;7,54;8,51;9,48;10,45;11,42;12,39;13,36;14,33;15,30

# Alternative system Enchant Scroll Jewelry
EnableEnchantChanceScrollJewelry = False
ChanceScrollJewelryList = 3,66;4,63;5,60;6,57;7,54;8,51;9,48;10,45;11,42;12,39;13,36;14,33;15,30

# -------------------------------------------- #
# -    Config Chance Blessed Enchant Itens   - #
# -------------------------------------------- #
# Alternative system Enchant Blessed Weapon
EnableEnchantChanceBlessedWeapon = False
ChanceBlessedWeaponList = 3,66;4,63;5,60;6,57;7,54;8,51;9,48;10,45;11,42;12,39;13,36;14,33;15,30

# Alternative system Enchant Blessed Armor
EnableEnchantChanceBlessedArmor = False
ChanceBlessedArmorList = 3,66;4,63;5,60;6,57;7,54;8,51;9,48;10,45;11,42;12,39;13,36;14,33;15,30

# Alternative system Enchant Blessed Jewelry
EnableEnchantChanceBlessedJewelry = False
ChanceBlessedJewelryList = 3,66;4,63;5,60;6,57;7,54;8,51;9,48;10,45;11,42;12,39;13,36;14,33;15,30

# -------------------------------------------- #
# -    Config Chance Crystal Enchant Itens   - #
# -------------------------------------------- #
# Alternative system Enchant Crystal Weapon
EnableEnchantChanceCrystalWeapon = False
ChanceCrystalWeaponList = 3,66;4,63;5,60;6,57;7,54;8,51;9,48;10,45;11,42;12,39;13,36;14,33;15,30

# Alternative system Enchant Crystal Armor
EnableEnchantChanceCrystalArmor = False
ChanceCrystalArmorList = 3,66;4,63;5,60;6,57;7,54;8,51;9,48;10,45;11,42;12,39;13,36;14,33;15,30

# Alternative system Enchant Crystal Jewelry
EnableEnchantChanceCrystalJewelry = False
ChanceCrystalJewelryList = 3,66;4,63;5,60;6,57;7,54;8,51;9,48;10,45;11,42;12,39;13,36;14,33;15,30

# ------------------------ #
# - Vip Enchant Config   - #
# ------------------------ #
# if the player is Vip, he receive a higher % of enchant
# Default = False
VipEnchantEnabled = True

# % Chance of succeeding to enchant an item when it has a chance of breaking
# Default: 72 | 58 | 61
EnchantChanceWeaponVip = 75
EnchantChanceArmorVip = 75
EnchantChanceJewelryVip = 75

# Chance a Crystal Enchant Scroll will succeed after safe enchant.
# Default: 100 | 100 | 100
EnchantChanceWeaponCrystalVip = 100
EnchantChanceArmorCrystalVip = 100
EnchantChanceJewelryCrystalVip = 100

# Chance a Blessed Enchant Scroll will succeed after safe enchant.
# Default: 85 | 85 | 85
EnchantChanceWeaponBlessedVip = 85
EnchantChanceArmorBlessedVip = 85
EnchantChanceJewelryBlessedVip = 85

# If EnchantSafeMax is set to for Ex '8' the item will be safely enchanted to '8'
# regardless of enchant chance(default = 3 for EnchantSafeMax and default = 4 for EnchantSafeMaxFull)
# EnchantSafeMaxFull is for full body armor (upper and lower)
# SHOULD BE > 0
EnchantSafeMax = 3
EnchantSafeMaxFull = 3

# Enchant limit [default = 0 (unlimited)]
EnchantMaxWeapon = 16
EnchantMaxArmor = 16
EnchantMaxJewelry = 16

# Enchant limit Custom
# Ex : EnchantMaxItem == 99910,20;99911,20;
# Default : 0 | 0
EnchantMaxItem = 0,0

# ------------------------------------------------------------------------- #
# - EnchantMaxAllowed is if any player has bigger enchant gets banned.    - #
# - EnchantMax is what max value can be put by scrols.                    - #
# ------------------------------------------------------------------------- #
# Default: 65535 | 65535 | 65535
EnchantMaxAllowedWeapon = 16
EnchantMaxAllowedArmor = 16
EnchantMaxAllowedJewelry = 16

# ------------------------------------------------------------------- #
# -                  OVER ENCHANT CONFIGURATION                     - #
# ------------------------------------------------------------------- #
# - Protection against Corrupt GMs!                                 - #
# - This protection will ban both GM and Edited character           - #
# - if a GM tries to enchant a NON GM player above the below value. - #
# - Over Enchant Protection                                         - #
# - Enable/Disable Over Enchant Protection                          - #
# ------------------------------------------------------------------- #
OverEnchantProtection = True
GMOverEnchant = 16

# If player isn't Gm and has items with Enchant Over +11 he will be kicked.
# set the maximum value, default 11.
EnchantKick = 16

# Enchant Hero Weapons
# This will allow enchanting hero weapons
# Default: False
EnchantHeroWeapons = False

# ----------------------------------- #
# - Increase Dwarfs Enchant Chances - #
# ----------------------------------- #
# Enable Dwarfs Enchant Bonus
EnableDwarfEnchantBonus = True

# Dwarfs Enchant Minimum Level
DwarfEnchantMinLevel = 60

# How More Chance is Added To Enchant
DwarfEncahntBonus = 5

# Alternative Enchant Value.
# Instead of enchanting with a scroll 1 by 1
# the scroll will be enchanting by the value u've set.
# Example: if value 5 from 5 will go to 10 and from 10 to 15
AlternativeEnchantValue = 1
```

**Comment by AnibalDuarte** [comment]
Alterei 

EnableDwarfEnchantBonus = False

VipEnchantEnabled = False

Erro persiste.

**Comment by AnibalDuarte** [comment]
Erro encontrado:

Tem um NPE na função de encantamento. Se o item não está na lista de configuração do EnchantMaxItem ele não pode ser encantado!

Solução paliativa temporária: colocar todas as armas e armaduras na lista de config/main/enchant.properties .

_PS.: a lista a seguir considera o Max Enchant 16. Se seu Max Enchant for direcente substitua o 16 pela quantidade._

`
EnchantMaxItem = 40,16;45,16;46,16;47,16;58,16;59,16;60,16;61,16;62,16;63,16;64,16;117,16;119,16;347,16;348,16;349,16;350,16;351,16;352,16;353,16;354,16;355,16;356,16;357,16;358,16;359,16;360,16;361,16;362,16;363,16;364,16;365,16;366,16;367,16;368,16;369,16;370,16;371,16;372,16;373,16;374,16;375,16;376,16;377,16;378,16;379,16;380,16;381,16;382,16;383,16;384,16;385,16;386,16;387,16;388,16;389,16;391,16;392,16;393,16;394,16;395,16;396,16;397,16;398,16;399,16;400,16;401,16;402,16;403,16;404,16;405,16;406,16;407,16;408,16;409,16;410,16;411,16;413,16;414,16;415,16;416,16;417,16;418,16;419,16;420,16;421,16;422,16;423,16;424,16;432,16;433,16;434,16;435,16;436,16;437,16;438,16;439,16;440,16;441,16;442,16;443,16;444,16;445,16;446,16;447,16;448,16;449,16;450,16;451,16;452,16;453,16;454,16;455,16;456,16;457,16;458,16;459,16;460,16;465,16;466,16;467,16;468,16;469,16;470,16;471,16;472,16;473,16;474,16;475,16;476,16;477,16;478,16;479,16;480,16;481,16;482,16;483,16;484,16;486,16;487,16;488,16;489,16;490,16;491,16;492,16;493,16;494,16;495,16;496,16;497,16;498,16;499,16;500,16;501,16;502,16;503,16;504,16;505,16;506,16;507,16;508,16;509,16;510,16;511,16;512,16;513,16;514,16;515,16;516,16;517,16;518,16;519,16;520,16;521,16;522,16;523,16;524,16;525,16;526,16;527,16;528,16;529,16;530,16;531,16;532,16;533,16;534,16;535,16;536,16;537,16;538,16;539,16;540,16;541,16;542,16;543,16;544,16;545,16;546,16;547,16;548,16;549,16;550,16;551,16;552,16;553,16;554,16;555,16;556,16;557,16;558,16;559,16;560,16;561,16;562,16;563,16;564,16;565,16;566,16;567,16;568,16;569,16;570,16;571,16;572,16;573,16;574,16;575,16;576,16;577,16;578,16;579,16;580,16;581,16;582,16;583,16;584,16;585,16;586,16;587,16;588,16;589,16;590,16;591,16;592,16;593,16;594,16;595,16;596,16;597,16;598,16;599,16;600,16;601,16;602,16;603,16;604,16;605,16;606,16;607,16;608,16;609,16;610,16;611,16;612,16;613,16;614,16;615,16;616,16;617,16;618,16;619,16;620,16;621,16;622,16;623,16;677,16;678,16;679,16;680,16;681,16;682,16;683,16;684,16;685,16;847,16;848,16;849,16;850,16;851,16;852,16;853,16;854,16;855,16;856,16;857,16;858,16;859,16;860,16;861,16;862,16;863,16;864,16;865,16;866,16;867,16;868,16;869,16;870,16;871,16;872,16;873,16;874,16;879,16;880,16;881,16;882,16;883,16;884,16;885,16;886,16;887,16;888,16;889,16;890,16;891,16;892,16;893,16;894,16;895,16;896,16;897,16;898,16;899,16;900,16;901,16;902,16;903,16;904,16;905,16;910,16;911,16;912,16;913,16;914,16;915,16;916,16;917,16;918,16;919,16;920,16;921,16;922,16;923,16;924,16;925,16;926,16;927,16;928,16;929,16;930,16;931,16;932,16;933,16;934,16;935,16;936,16;1120,16;1123,16;1124,16;1125,16;1126,16;1127,16;1128,16;1149,16;2376,16;2377,16;2378,16;2379,16;2380,16;2381,16;2382,16;2383,16;2384,16;2385,16;2387,16;2388,16;2389,16;2390,16;2391,16;2392,16;2393,16;2394,16;2395,16;2396,16;2397,16;2398,16;2399,16;2400,16;2401,16;2402,16;2403,16;2404,16;2405,16;2406,16;2407,16;2408,16;2409,16;2410,16;2411,16;2412,16;2413,16;2414,16;2415,16;2416,16;2417,16;2418,16;2419,16;2420,16;2421,16;2422,16;2423,16;2424,16;2425,16;2426,16;2427,16;2428,16;2429,16;2430,16;2431,16;2432,16;2433,16;2434,16;2435,16;2436,16;2437,16;2438,16;2439,16;2440,16;2441,16;2442,16;2443,16;2444,16;2445,16;2446,16;2447,16;2448,16;2449,16;2450,16;2451,16;2452,16;2453,16;2454,16;2455,16;2456,16;2457,16;2458,16;2459,16;2460,16;2461,16;2462,16;2463,16;2464,16;2465,16;2466,16;2467,16;2468,16;2469,16;2470,16;2471,16;2472,16;2473,16;2474,16;2475,16;2476,16;2477,16;2478,16;2479,16;2480,16;2481,16;2482,16;2483,16;2484,16;2485,16;2486,16;2487,16;2488,16;2489,16;2492,16;4224,16;4225,16;4226,16;4227,16;4228,16;4229,16;4230,16;4231,16;5287,16;5288,16;5289,16;5290,16;5291,16;5293,16;5294,16;5295,16;5296,16;5297,16;5298,16;5299,16;5300,16;5301,16;5302,16;5303,16;5304,16;5305,16;5306,16;5307,16;5308,16;5309,16;5310,16;5311,16;5312,16;5313,16;5314,16;5316,16;5317,16;5318,16;5319,16;5320,16;5321,16;5322,16;5323,16;5324,16;5325,16;5326,16;5327,16;5328,16;5329,16;5330,16;5331,16;5709,16;5710,16;5711,16;5712,16;5713,16;5714,16;5715,16;5716,16;5717,16;5718,16;5719,16;5720,16;5721,16;5722,16;5723,16;5724,16;5725,16;5726,16;5727,16;5728,16;5729,16;5730,16;5731,16;5732,16;5733,16;5734,16;5735,16;5736,16;5737,16;5738,16;5739,16;5740,16;5765,16;5766,16;5767,16;5768,16;5769,16;5770,16;5771,16;5772,16;5773,16;5774,16;5775,16;5776,16;5777,16;5778,16;5779,16;5780,16;5781,16;5782,16;5783,16;5784,16;5785,16;5786,16;5787,16;5788,16;6323,16;6324,16;6325,16;6326,16;6327,16;6328,16;6373,16;6374,16;6375,16;6376,16;6378,16;6379,16;6380,16;6381,16;6382,16;6383,16;6384,16;6385,16;6386,16;6656,16;6657,16;6658,16;6659,16;6660,16;6661,16;6662,16;6674,16;6675,16;6676,16;6677,16;6679,16;6680,16;6681,16;6682,16;6683,16;6684,16;6685,16;6686,16;6687,16;6724,16;6725,16;6726,16;7850,16;7851,16;7852,16;7853,16;7854,16;7855,16;7856,16;7857,16;7858,16;7859,16;7860,16;7861,16;7862,16;7863,16;7864,16;7865,16;7866,16;7867,16;7868,16;7869,16;7870,16;7871,16;7872,16;7873,16;7874,16;7875,16;7876,16;7877,16;7878,16;7879,16;8191,16;69,16;70,16;71,16;72,16;73,16;74,16;75,16;76,16;77,16;78,16;79,16;80,16;81,16;82,16;83,16;84,16;85,16;86,16;88,16;89,16;90,16;91,16;92,16;93,16;94,16;95,16;96,16;97,16;98,16;101,16;103,16;104,16;105,16;106,16;107,16;108,16;109,16;110,16;111,16;123,16;124,16;125,16;126,16;127,16;128,16;129,16;130,16;131,16;132,16;133,16;134,16;135,16;136,16;137,16;138,16;139,16;140,16;141,16;142,16;143,16;144,16;145,16;146,16;147,16;148,16;149,16;150,16;151,16;156,16;157,16;158,16;159,16;160,16;161,16;162,16;163,16;164,16;165,16;166,16;167,16;168,16;169,16;170,16;171,16;172,16;173,16;174,16;175,16;178,16;179,16;180,16;181,16;182,16;183,16;184,16;185,16;186,16;187,16;188,16;189,16;190,16;191,16;192,16;193,16;194,16;195,16;196,16;197,16;198,16;199,16;200,16;201,16;202,16;203,16;204,16;205,16;206,16;207,16;208,16;209,16;210,16;211,16;212,16;213,16;214,16;220,16;221,16;222,16;223,16;224,16;225,16;226,16;227,16;228,16;229,16;230,16;231,16;232,16;233,16;234,16;235,16;236,16;237,16;238,16;239,16;240,16;241,16;242,16;243,16;258,16;259,16;260,16;261,16;262,16;263,16;264,16;265,16;266,16;267,16;268,16;269,16;270,16;274,16;275,16;276,16;277,16;278,16;279,16;280,16;281,16;282,16;283,16;284,16;285,16;286,16;287,16;288,16;289,16;290,16;291,16;292,16;293,16;294,16;295,16;296,16;297,16;298,16;299,16;300,16;301,16;302,16;303,16;304,16;305,16;306,16;307,16;312,16;313,16;314,16;315,16;316,16;317,16;318,16;319,16;320,16;321,16;322,16;323,16;324,16;325,16;326,16;327,16;328,16;329,16;330,16;331,16;332,16;333,16;334,16;335,16;336,16;337,16;338,16;339,16;340,16;341,16;342,16;343,16;344,16;345,16;346,16;626,16;627,16;628,16;629,16;630,16;631,16;632,16;633,16;634,16;635,16;636,16;637,16;638,16;639,16;640,16;641,16;642,16;643,16;644,16;645,16;646,16;647,16;648,16;649,16;650,16;651,16;652,16;653,16;654,16;655,16;656,16;657,16;658,16;659,16;660,16;661,16;662,16;663,16;664,16;665,16;666,16;667,16;668,16;669,16;670,16;671,16;672,16;673,16;674,16;749,16;1376,16;1471,16;1472,16;1660,16;2493,16;2494,16;2495,16;2496,16;2497,16;2498,16;2499,16;2500,16;2502,16;2503,16;2504,16;2516,16;2517,16;2518,16;2519,16;2520,16;2521,16;2522,16;2523,16;2524,16;2525,16;2526,16;2527,16;2528,16;2529,16;2530,16;2531,16;2532,16;2533,16;2534,16;2535,16;2536,16;2537,16;2538,16;2539,16;2540,16;2541,16;2542,16;2543,16;2544,16;2545,16;2546,16;2547,16;2548,16;2549,16;2550,16;2551,16;2552,16;2553,16;2554,16;2555,16;2556,16;2557,16;2558,16;2559,16;2560,16;2561,16;2562,16;2563,16;2564,16;2565,16;2566,16;2567,16;2568,16;2569,16;2570,16;2571,16;2572,16;2573,16;2574,16;2575,16;2576,16;2577,16;2578,16;2579,16;2580,16;2581,16;2582,16;2583,16;2584,16;2585,16;2586,16;2587,16;2588,16;2589,16;2590,16;2591,16;2592,16;2593,16;2594,16;2595,16;2596,16;2597,16;2598,16;2599,16;2600,16;2601,16;2602,16;2603,16;2604,16;2605,16;2606,16;2607,16;2608,16;2609,16;2610,16;2611,16;2612,16;2613,16;2614,16;2615,16;2616,16;2617,16;2618,16;2619,16;2620,16;2621,16;2622,16;2623,16;2624,16;2625,16;2626,16;3937,16;3938,16;3939,16;4028,16;4219,16;4220,16;4221,16;4222,16;4223,16;4233,16;4681,16;4682,16;4683,16;4684,16;4685,16;4686,16;4687,16;4688,16;4689,16;4690,16;4691,16;4692,16;4693,16;4694,16;4695,16;4696,16;4697,16;4698,16;4699,16;4700,16;4701,16;4702,16;4703,16;4704,16;4705,16;4706,16;4707,16;4708,16;4709,16;4710,16;4711,16;4712,16;4713,16;4714,16;4715,16;4716,16;4717,16;4718,16;4719,16;4720,16;4721,16;4722,16;4723,16;4724,16;4725,16;4726,16;4727,16;4728,16;4729,16;4730,16;4731,16;4732,16;4733,16;4734,16;4735,16;4736,16;4737,16;4738,16;4739,16;4740,16;4741,16;4742,16;4743,16;4744,16;4745,16;4746,16;4747,16;4748,16;4749,16;4750,16;4751,16;4752,16;4753,16;4754,16;4755,16;4756,16;4757,16;4758,16;4759,16;4760,16;4761,16;4762,16;4763,16;4764,16;4765,16;4766,16;4767,16;4768,16;4769,16;4770,16;4771,16;4772,16;4773,16;4774,16;4775,16;4776,16;4777,16;4778,16;4779,16;4780,16;4781,16;4782,16;4783,16;4784,16;4785,16;4786,16;4787,16;4788,16;4789,16;4790,16;4791,16;4792,16;4793,16;4794,16;4795,16;4796,16;4797,16;4798,16;4799,16;4800,16;4801,16;4802,16;4803,16;4804,16;4805,16;4806,16;4807,16;4808,16;4809,16;4810,16;4811,16;4812,16;4813,16;4814,16;4815,16;4816,16;4817,16;4818,16;4819,16;4820,16;4821,16;4822,16;4823,16;4824,16;4825,16;4826,16;4827,16;4828,16;4829,16;4830,16;4831,16;4832,16;4833,16;4834,16;4835,16;4836,16;4837,16;4838,16;4839,16;4840,16;4841,16;4842,16;4843,16;4844,16;4845,16;4846,16;4847,16;4848,16;4849,16;4850,16;4851,16;4852,16;4853,16;4854,16;4855,16;4856,16;4857,16;4858,16;4859,16;4860,16;4861,16;4862,16;4863,16;4864,16;4865,16;4866,16;4867,16;4868,16;4869,16;4870,16;4871,16;4872,16;4873,16;4874,16;4875,16;4876,16;4877,16;4878,16;4879,16;4880,16;4881,16;4882,16;4883,16;4884,16;4885,16;4886,16;4887,16;4888,16;4889,16;4890,16;4891,16;4892,16;4893,16;4894,16;4895,16;4896,16;4897,16;4898,16;4899,16;4900,16;4901,16;4902,16;4903,16;4904,16;4905,16;5128,16;5130,16;5131,16;5132,16;5233,16;5285,16;5286,16;5292,16;5315,16;5596,16;5597,16;5598,16;5599,16;5600,16;5601,16;5602,16;5603,16;5604,16;5605,16;5606,16;5607,16;5608,16;5609,16;5610,16;5611,16;5612,16;5613,16;5614,16;5615,16;5616,16;5617,16;5618,16;5619,16;5620,16;5621,16;5622,16;5623,16;5624,16;5625,16;5626,16;5627,16;5628,16;5629,16;5630,16;5631,16;5632,16;5633,16;5634,16;5635,16;5636,16;5637,16;5638,16;5639,16;5640,16;5641,16;5642,16;5643,16;5644,16;5645,16;5646,16;5647,16;5648,16;5649,16;5704,16;5705,16;5706,16;5791,16;5792,16;5793,16;5794,16;5795,16;5796,16;5797,16;5798,16;5799,16;5800,16;5801,16;5802,16;6307,16;6308,16;6309,16;6310,16;6311,16;6312,16;6313,16;6314,16;6315,16;6347,16;6348,16;6349,16;6356,16;6357,16;6358,16;6359,16;6364,16;6365,16;6366,16;6367,16;6368,16;6369,16;6370,16;6371,16;6372,16;6377,16;6579,16;6580,16;6581,16;6582,16;6583,16;6584,16;6585,16;6586,16;6587,16;6588,16;6589,16;6590,16;6591,16;6592,16;6593,16;6594,16;6595,16;6596,16;6597,16;6598,16;6599,16;6600,16;6601,16;6602,16;6603,16;6604,16;6605,16;6606,16;6607,16;6608,16;6609,16;6610,16;6678,16;6902,16;7015,16;7575,16;7576,16;7577,16;7578,16;7701,16;7702,16;7703,16;7704,16;7705,16;7706,16;7707,16;7708,16;7709,16;7710,16;7711,16;7712,16;7713,16;7714,16;7715,16;7716,16;7717,16;7718,16;7719,16;7720,16;7721,16;7722,16;7723,16;7724,16;7810,16;7811,16;7812,16;7813,16;7814,16;7815,16;7834,16;7880,16;7881,16;7882,16;7883,16;7884,16;7885,16;7886,16;7887,16;7888,16;7889,16;7890,16;7891,16;7892,16;7893,16;7894,16;7895,16;7896,16;7897,16;7898,16;7899,16;7900,16;7901,16;7902,16;7903,16;8102,16;8103,16;8104,16;8105,16;8106,16;8107,16;8108,16;8109,16;8110,16;8111,16;8112,16;8113,16;8114,16;8115,16;8116,16;8117,16;8118,16;8119,16;8120,16;8121,16;8122,16;8123,16;8124,16;8125,16;8126,16;8127,16;8128,16;8129,16;8130,16;8131,16;8132,16;8133,16;8134,16;8135,16;8136,16;8137,16;8138,16;8139,16;8140,16;8141,16;8142,16;8143,16;8144,16;8145,16;8146,16;8147,16;8148,16;8149,16;8150,16;8151,16;8152,16;8190,16;8203,16;8205,16;8206,16;8207,16;8208,16;8212,16;8213,16;8215,16;8217,16;8218,16;8219,16;8220,16;8222,16;8350,16;8527,16;8528,16;8531,16;8532,16;8533,16;8678,16;8679,16;8680,16;8681,16;8682,16;8683,16;8684,16;8685,16;8686,16;8687,16;8688,16;8689,16;8788,16;8789,16;8790,16;8791,16;8792,16;8793,16;8794,16;8795,16;8796,16;8797,16;8798,16;8799,16;8800,16;8801,16;8802,16;8803,16;8804,16;8805,16;8806,16;8807,16;8808,16;8809,16;8810,16;8811,16;8812,16;8813,16;8814,16;8815,16;8816,16;8817,16;8818,16;8819,16;8820,16;8938,16;9136,16;9137,16;
`

**Comment by Tayran** [comment]
Muito obrigado por ajudar o projeto, não precisava criar uma lista tão grande assim e que gasta tanto trabalho para algo que deve ser resolvido no Core, eu fiz um commit, vou disponibilizar a nova revisão em breve.

**Comment by AnibalDuarte** [comment]
Trabalho pra fazer a lista não deu, porque eu só dei um select em uma tabela pegando todos os itens com crystal_type d/c/b/a/s e removendo todos os que são temporários e depois concatenei **,16;** do lado de todos os IDs.
